version: '3.8'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource
    networks:
      - prom

volumes:
  grafana-storage:

networks:
  prom:
    driver: bridge